title: "aarch64 osdev notes"
baseurl: /aarch64-osdev-notes
updated: "2021-03-15"

collections_dir: notes
collections:
  aarch64:
    title: "AArch64"
    output: true
  rockchip:
    title: "Rockchip"
    output: true
  rockpis:
    title: "ROCK Pi S"
    output: true
