title: "AArch64 osdev notes"
baseurl: /aarch64-osdev-notes
updated: "2021-02-25"

collections_dir: notes
collections:
  rockchip:
    title: "Rockchip"
    output: true
  rockpis:
    title: "ROCK Pi S"
    output: true
